name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install required dependencies
      run: npm install
    - name: production
      run: gulp produce
